language: java
jdk:
- openjdk8
env:
  global:
  - AWS_DEFAULT_REGION: ap-southeast-2
  - AWS_ACCESS_KEY_ID: AKIA2AV2YTL6SUSQP56W
  # AWS_SECRET_ACCESS_KEY, /geodesy-operations/iam-user/travis-ci/access-key/AKIA2AV2YTL6SUSQP56W/secret-access-key
  - secure: PvG73qT+iLCcYSUydBJS+JisXELniiIfS2dJ7Z/SS2hBM5zCZ3z46WDaMNmYku0BPdR6/9TbjVD2TWhU9BYr9hdnHUmu8aF+x4BAcY3RviSCWjOI2iiCv893MmuUCG4WETAbKrnoEQymzxBHO2bdvfh5NYEQDDlHQfQT2GGvgBoFIgcZkvfhIDzxp3tb++I5j+TVhcHBdqC+f9w3SCx13QSMiD5bzJML4UugNng0FRhSjAuaBkIlw00uMd30hP3DbIkqZ+JBzebyCPe4/hqFrbkV3z9LWE79jGKJ+ZhKtKMUqOn0N+fUZ49JyDFqeP70neiA3wS0oQyXerDjcp/fr+5w4sJ0NR7NtaXbKAvXq1v5sjyM8yncF/kn6lPXq5xq5tBzgJnFoLdJdSgKOCMw1Dru03eXjV6loQoLzpFgixyVXNddkz1jPhLQ6jMyNX9mwgWYQpvoKKGSnMuGYjAb45jUuXQF+gOlLCaUvVsepg83IvIw2tDqG7gqR/77h/NksuEaHU4D4DMWpxfRQfeaBtIkxeoDtyxgm4TxCty5t8VYKHQUNQsM9yjqqVcvuuA/E3bcVgNIg4K/N2rP3yYaNApZLD15JsDMJNI6Iku39Mo2XJ5ZddYQANRj0grSUhpgxn3RhTntKbmzlfXwiJ/iFHHHwPqV9m1jaXb0lRinZtM=
