language: java
jdk:
- openjdk8
env:
  global:
  - AWS_DEFAULT_REGION: ap-southeast-2
  - AWS_ACCESS_KEY_ID: AKIAJBSOFDJSDGWCKQ3Q
  # AWS_SECRET_ACCESS_KEY, /geodesy-operations/iam-user/geodesy-operations-pipelines-dev/access-key/AKIAJBSOFDJSDGWCKQ3Q/secret-access-key
  - secure: rwwB+ruT/oriO/k+JfSQL+nHITOI5y2CXeevUSam7GH+ZQM5G0HSGwiF9vGJKmVbE5ZdbomBHdNmgqv9rMOZoCe8NZ7hW6hsWPxF0gT+XM2SYeOl4TN2/Ywtt51udGje022tLN2746XfwoWf5zVNKXpR0wOltjWXkDv6k5aCajZ0J7Ip31Wxs24VHeOccZZu85eOp8LRznfKEpLJ222yOW7JIp3dgfW1TKafQKWo894xxB7P/ittPHw9VkzSkM86hkv+8hByfBE5gfQxLXk2Jm8r14zbScaYU8LuQ7rBU1nQJbXyP0cZa1iwbuL3JKDG+CiAM190FWlmmfyIDSp8aoQWqPwdaPCkXQKiJdLwtDozDh0RKndUcnkQPkQD/k47fDCxZnXo9067gWDbAltJgY5sFqM+giff6jcMSRpzKyb4W/1WYwGyrNjMgp26RUeO9pnJc869MTUO//nSgB6ui13JwR5nMM/mWIVTtK6xsaz2H6hju32dLd+7tMShV5IOzR1/7MNd6+EVsEbggMmzndyyPssbr66ZCXNgWkJy+Mo2Gl4zDvC5GF7133Wyv/OsUIQDoBS4qNV1fr0TLzcJqBekf+LO4qiTwuLQlezcpa5c9iVP2uSgGFKRUFIhzxO0vzbaPvNHKvB8lYXoiJGuXUvjcRkfG9E3HEbdU430aes=
